### ISSUE TITLE
你好，看您的代码里还有i3d能也上传进去吗

### ISSUE THREAD

**Issue by machineNo6** [FenHua/SVA#1]
elif model_name == 'i3d':
        from models.I3D.I3D import generate_model_i3d
        model = generate_model_i3d(dataset_name)
        model.eval()

**Comment by machineNo6** [comment]
And also
Traceback (most recent call last):
  File "untargeted_attack_test.py", line 20, in <module>
    model = generate_model(model_name, dataset_name)        # get the training dataset
  File "/home/chentong/SVA/Utils/utils.py", line 145, in generate_model
    model = generate_model_lrcn(dataset_name)
  File "/home/chentong/SVA/models/LRCN/LRCN.py", line 12, in generate_model_lrcn
    model = get_model(checkpoint,num_class)
  File "/home/chentong/SVA/models/LRCN/LRCN_model.py", line 39, in get_model
    model_info = torch.load(checkpoint)
  File "/home/chentong/anaconda3/envs/sva/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/chentong/anaconda3/envs/sva/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/chentong/anaconda3/envs/sva/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/LRCN/checkpoints/hmdb51_save_best.pth'
